### PR TITLE
EN-2411 frontend-libraries (apimanager) dependency update

### PR DESCRIPTION
**Pull request by jeffgo10**
current version is using entando/apimanager 1.0.1 and since we have already updated apimanager in app-builder to 3.0.2, we should update this plugin to avoid conflict.

### CODE REVIEW

**Comment by entando-service** [comment]
All is Well

**Comment by gidesan** [comment]
@jeffgo10 never been on this repo
@fedelocci can you approve this PR if it looks good?

**Comment by alepintus** [comment]
Hi @nicpuddu ,
could yoo please have a look at this PR?
Thanks

**Comment by jeffgo10** [comment]
hi @alepintus I have made a little change in package.json on lodash version to avoid conflict from the app-builder. I have also created a PR in app-builder for you to review. thanks

**Comment by entando-service** [comment]
All is Well

**Pull request merged**
