### PR TITLE
EN6-143 Changing attributes to match the new requirements

### PR DESCRIPTION
**Pull request by BrenoQVDS**
Due to new requirements the value for searchableOptionSupported and indexableOptionSupported needed to be changed to some attributes. This build will only work after this PR is ready:
https://github.com/entando/entando-core/pull/838

### CODE REVIEW

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by ffleandro** [comment]
Retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by ffleandro** [comment]
Retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
All is Well

**Pull request merged**
