### PR TITLE
ENG-139 Adding validation for bulk status update

### PR DESCRIPTION
**Pull request by BrenoQVDS**

### CODE REVIEW

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by BrenoQVDS** [comment]
test this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by BrenoQVDS** [comment]
test this

**Comment by BrenoQVDS** [comment]
this please

**Comment by BrenoQVDS** [comment]
test this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by BrenoQVDS** [comment]
test this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by BrenoQVDS** [comment]
test this please

**Comment by entando-service** [comment]
All is Well

**Pull request merged**
