### PR TITLE
ENG-163 Creating test for checkbox attribute

### PR DESCRIPTION
**Pull request by BrenoQVDS**

### CODE REVIEW

**Comment by BrenoQVDS** [comment]
This will work only when this PR is merged:
https://github.com/entando/entando-core/pull/856

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by BrenoQVDS** [comment]
Restest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by BrenoQVDS** [comment]
Retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by BrenoQVDS** [comment]
Retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by BrenoQVDS** [comment]
Retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by BrenoQVDS** [comment]
Retest this please

**Comment by entando-service** [comment]
All is Well

**Pull request merged**
