### PR TITLE
[5.0.3] EN-2191-503-frame-widget-labels-fix

### PR DESCRIPTION
**Pull request by alepintus**
Hi @joewhite101 @DMinnai ,
this is the cherry-pick from [this master commit](https://github.com/entando/entando-components/pull/432/commits/b6a59d88a4a81be783a6c11ada3e58ad16243fcc) .
Could you please review this PR?

Thanks!

### CODE REVIEW

**Comment by entando-service** [comment]
All is Well

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by alepintus** [comment]
Retest this please

**Comment by entando-service** [comment]
All is Well

**Pull request merged**
