### PR TITLE
ENQT-130 fix core dependencies

### PR DESCRIPTION
**Pull request by Rguerrini**

### CODE REVIEW

**Comment by entando-service** [comment]
Can one of the admins verify this patch?

**Comment by nicpuddu** [comment]
risolvere le missing properties

**Comment by nicpuddu** [comment]
test this please

**Comment by entando-service** [comment]
All is Well

**Comment by Rguerrini** [comment]
Aggiunti key ed etichette

**Comment by entando-service** [comment]
All is Well

**Pull request merged**
