### PR TITLE
En 2266 master archetype sample bpm widgets

### PR DESCRIPTION
**Pull request by DMinnai**

### CODE REVIEW

**Comment by DMinnai** [comment]
retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by pietrangelo** [comment]
retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by pietrangelo** [comment]
retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
All is Well

**Pull request merged**
