### PR TITLE
EN-2225-drag-and-drop-case-progress-status

### PR DESCRIPTION
**Pull request by alepintus**
Hi @joewhite101,
this is the cherry pick from [this PR](https://github.com/entando/entando-components/pull/401),
this PR should be merged after [this other components PR](https://github.com/entando/entando-components/pull/391)

Could you please have a look?
Thanks!

fyi @DMinnai : I already updated [your PR](https://github.com/entando/entando-components/pull/391) with the latest changes from the master branch

### CODE REVIEW

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by alepintus** [comment]
retest this please

**Comment by entando-service** [comment]
All is Well

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
All is Well

**Pull request merged**
