### PR TITLE
ENG-128 Returning unprotected url if user has permission

### PR DESCRIPTION
**Pull request by BrenoQVDS**

### CODE REVIEW

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by BrenoQVDS** [comment]
restes this please

**Comment by BrenoQVDS** [comment]
restest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
All is Well

**Review by joewhite101 — APPROVED** [review]
Looks good.

**Pull request merged**
