### PR TITLE
Add-claim-task-master

### PR DESCRIPTION
**Pull request by alepintus**
Hi @joewhite101 ,
this is the cherry-pick from [this PR](https://github.com/entando/entando-components/pull/477).

Thanks!

### CODE REVIEW

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by alepintus** [comment]
Retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by alepintus** [comment]
Retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by alepintus** [comment]
Please retest this

**Comment by alepintus** [comment]
Retest this please

**Comment by entando-service** [comment]
All is Well

**Pull request merged**
