### PR TITLE
EN-1924-CMS-menu-contents-settings-labels

### PR DESCRIPTION
**Pull request by alepintus**
Hey @joewhite101 @eugeniosant ,
Label tests added.
It should be merged a the same time with the entando-core PR below:

https://github.com/entando/entando-core/pull/583

Thanks!

### CODE REVIEW

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by alepintus** [comment]
retest this please

**Comment by entando-service** [comment]
All is Well

**Pull request merged**
