### PR TITLE
Update lucene version

### PR DESCRIPTION
**Pull request by joewhite101**
Depends on the merging of this PR in core:
https://github.com/entando/entando-core/pull/734

### CODE REVIEW

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by pietrangelo** [comment]
retest this please

**Comment by eugeniosant** [comment]
retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by pietrangelo** [comment]
retest this please

**Comment by entando-service** [comment]
All is Well

**Pull request merged**
