### PR TITLE
ENG-416 content type usage details

### PR DESCRIPTION
**Pull request by firegloves**
Can anyone check my implementation please?

### CODE REVIEW

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by alepintus** [comment]
Retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by firegloves** [comment]
Retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by firegloves** [comment]
Retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by firegloves** [comment]
Retest this please

**Comment by entando-service** [comment]
All is Well

**Pull request merged**
