### PR TITLE
Merge pull request #424 from entando/fix-header-inspinia

### PR DESCRIPTION
**Pull request by joewhite101**
Fix labels in case management samples

### CODE REVIEW

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by joewhite101** [comment]
Retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by alepintus** [comment]
Retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by joewhite101** [comment]
Retest this please

**Comment by entando-service** [comment]
All is Well

**Pull request merged**
