### PR TITLE
ENG-140 Tests for change in the core where the null widgets are left …

### PR DESCRIPTION
**Pull request by BrenoQVDS**
…on the response

### CODE REVIEW

**Comment by BrenoQVDS** [comment]
This will fail until the PR from the core is merged: https://github.com/entando/entando-core/pull/847

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by BrenoQVDS** [comment]
Retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by BrenoQVDS** [comment]
Retest this please

**Comment by entando-service** [comment]
All is Well

**Pull request merged**
