### PR TITLE
ENQT-173: plugin Survey - port to 4.3

### PR DESCRIPTION
**Pull request by giorgio94c**

### CODE REVIEW

**Comment by entando-service** [comment]
Can one of the admins verify this patch?

**Comment by nicpuddu** [comment]
test this please

**Comment by nicpuddu** [comment]
sistemare missing properties

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by nicpuddu** [comment]
test this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by nicpuddu** [comment]
risultano conflicts da risolvere @giorgio94c

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Pull request closed without merging**
