### PR TITLE
ENQT-171: plugin Action Logger - port to 4.3

### PR DESCRIPTION
**Pull request by giorgio94c**

### CODE REVIEW

**Comment by entando-service** [comment]
Can one of the admins verify this patch?

**Comment by nicpuddu** [comment]
add to whitelist

**Comment by nicpuddu** [comment]
test this please

**Comment by nicpuddu** [comment]
sistemare le missing properties

**Comment by entando-service** [comment]
All is Well

**Comment by entando-service** [comment]
All is Well

**Pull request merged**
