### PR TITLE
[5.0.1] En 1670 fix breadcrumb item

### PR DESCRIPTION
**Pull request by alessioscalici**

### CODE REVIEW

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by joewhite101** [comment]
Retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by eugeniosant** [comment]
Retest this please

**Comment by entando-service** [comment]
All is Well

**Pull request merged**
