### PR TITLE
SME-2 CMS APIs

### PR DESCRIPTION
**Pull request by eugeniosant**
This PR needs merge of PR [entando/entando-core#775](https://github.com/entando/entando-core/pull/777)

### CODE REVIEW

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by eugeniosant** [comment]
restart this please

**Comment by eugeniosant** [comment]
retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
All is Well

**Comment by entando-service** [comment]
All is Well

**Pull request merged**
