### PR TITLE
EN-2302 (master) Fixed content status issue for Content Workflow plugin

### PR DESCRIPTION
**Pull request by zonia3000**

### CODE REVIEW

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by zonia3000** [comment]
The main issue was a missing action method configuration inside `plugins/jpcontentworkflow/apsadmin/content/content.xml`

This caused the `ContentAction` inside CMS plugin to be called instead of its subclass inside Content Workflow plugin. As a consequence, the status dropdown contained wrong values and the "Choose an option" empty option was selected. This caused content status to be an empty string and that value was stored into the database causing a sequence of related issues.

This kind of issue could happen again if a new action method is added inside CMS `ContentAction` and the `content.xml` file inside Content Workflow plugin is not updated accordingly.
For this reason I added a check on `ContentActionHelper`, to avoid empty status could be stored into the database. The other changes are simply class tidy up.

**Comment by zonia3000** [comment]
retest this please

**Comment by entando-service** [comment]
All is Well

**Pull request merged**
