### PR TITLE
EN-2407 Added encryption to DE and BPM passwords.

### PR DESCRIPTION
**Pull request by zonia3000**
Retest this after [corresponding PR in core has been merged](https://github.com/entando/entando-core/pull/788) (already tested locally).

The password is encrypted before JAXB marshalling and decrypted after JAXB unmarshalling. This in handled by dedicated classes:

- [DigitalExchangeConfigXmlConverter](https://github.com/entando/entando-components/blob/EN-2407/plugins/entando-plugin-jpdigital-exchange/src/main/java/org/entando/entando/aps/system/services/digitalexchange/DigitalExchangeConfigXmlConverter.java) for DE
- [KieBpmConfigXMLConverter](https://github.com/entando/entando-components/blob/EN-2407/plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/KieBpmConfigXMLConverter.java) for BPM

Current encryption is done using Blowfish but it can easily replaced. The encryption key can be configured adding the following property to `src/main/config/security.properties`:

    algo.blowfish.key=mykey

---

Doing this I also noticed that the **jprestapi** plugin uses MOXy instead of the default JAXB implementation and this caused an incompatibility issue that forced me to change part of the code I've written in core.
It seems that MOXy is used only to support a particular JSON conversion in [JAXBHelper](https://github.com/entando/entando-components/blob/master/plugins/entando-plugin-jprestapi/src/main/java/org/entando/entando/plugins/jprestapi/aps/core/helper/JAXBHelper.java) class.
It seems also that the jprestapi plugin is currently used only by BPM plugin and I think that its functionalities could be replaced by using directly the Spring `RestTemplate` class.

### CODE REVIEW

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by alepintus** [comment]
Retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by zonia3000** [comment]
retest this please

**Comment by entando-service** [comment]
All is Well

**Pull request merged**
