### PR TITLE
EN-2421 DE signature validation

### PR DESCRIPTION
**Pull request by Kerruba**
Integration of components signature in the DE

### CODE REVIEW

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by zonia3000** [comment]
retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by zonia3000** [comment]
retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by Kerruba** [comment]
retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by zonia3000** [comment]
retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
All is Well

**Pull request merged**
