### PR TITLE
EN-2301 Oauth2/OIDC plugin

### PR DESCRIPTION
**Pull request by ampie**

### CODE REVIEW

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
All is Well

**Comment by joewhite101** [comment]
@eugeniosant Can you take a look at this PR? You can merge it if you're happy or let me know and i'll merge

**Pull request merged**
