### PR TITLE
ENQT-170: plugin TagCloud - port to 4.3

### PR DESCRIPTION
**Pull request by Rguerrini**

### CODE REVIEW

**Comment by nicpuddu** [comment]
risolvere i conflitti

**Comment by nicpuddu** [comment]
test this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by Rguerrini** [comment]
Conflitti risolti

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by nicpuddu** [comment]
test this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
All is Well

**Pull request merged**
