### PR TITLE
ENG-513 adding folderPath field and creating new list endpoint

### PR DESCRIPTION
**Pull request by BrenoQVDS**

### CODE REVIEW

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by BrenoQVDS** [comment]
retest please

**Comment by BrenoQVDS** [comment]
retest please

**Comment by BrenoQVDS** [comment]
retest this

**Comment by BrenoQVDS** [comment]
retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
All is Well

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by BrenoQVDS** [comment]
Restest this please

**Comment by entando-service** [comment]
All is Well

**Pull request merged**
