### PR TITLE
EN6-126 Fixed DELETE method by removing body from request; Added PUT …

### PR DESCRIPTION
**Pull request by ffleandro**
- Created PUT methods for editing CropRatios and Metadata
- Changed DELETE CropRatios and Metadata to don't send body
- Fixes EN6-53: 404 error codes on DELETE ContentSettings metadata and cropRatios methods

### CODE REVIEW

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by joewhite101** [comment]
Retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by ffleandro** [comment]
Retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by ffleandro** [comment]
Retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by ffleandro** [comment]
Jenkins corrupted some files. Will reopen a new PR.

**Pull request closed without merging**
