### PR TITLE
EN-2261-add-process-diagram-widget-to-Inspinia-BPM-default-widgets

### PR DESCRIPTION
**Pull request by alepintus**
Hi @joewhite101 ,
this is the cherry-pick for the commit of [this PR](https://github.com/entando/entando-components/pull/431)
Thanks!

### CODE REVIEW

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by joewhite101** [comment]
Retest this please

**Comment by entando-service** [comment]
All is Well

**Comment by entando-service** [comment]
All is Well

**Pull request merged**
