### PR TITLE
EN-2511 EN-2512 Removed support for Argon2, moved default TextEncryptor in components

### PR DESCRIPTION
**Pull request by zonia3000**
See also related PR in core: https://github.com/entando/entando-core/pull/804

### CODE REVIEW

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by zonia3000** [comment]
Test again after the PR in core has been merged (already tested locally)

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by joewhite101** [comment]
OBE

**Pull request closed without merging**
