### PR TITLE
Bugfix on Hypertext resource search with performace improvements; fix…

### PR DESCRIPTION
**Pull request by MEM2677**
- Fixes a bug related to the creation of a link to content / link to a resource from content edit.
- Performance improvement when creating a  link to resource

(Fixes https://jira.entando.org/browse/GIU-105?filter=-1)

### CODE REVIEW

**Comment by joewhite101** [comment]
Do these need to make their way to master?

**Comment by eugeniosant** [comment]
@joewhite101 After merge in v5.3 I'll make a PR for master

**Comment by joewhite101** [comment]
@eugeniosant 👍

**Comment by entando-service** [comment]
All is Well

**Pull request merged**
