### PR TITLE
EN6-209 Implementing create and update of imageAttributes and attachA…

### PR DESCRIPTION
**Pull request by BrenoQVDS**
…ttributes for contents

### CODE REVIEW

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by BrenoQVDS** [comment]
Retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
All is Well

**Comment by entando-service** [comment]
All is Well

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
All is Well

**Pull request merged**
