### PR TITLE
EN-1980 EN-1981 EN-1982 EN-1984 Support Date type, TextArea CheckBox and ListBox in PAM Forms

### PR DESCRIPTION
**Pull request by alepintus**
Hi @joewhite101 @eugeniosant,
support for Date type and TextArea in PAM Forms added.

Could you please have a look?
thanks!

Alessio

### CODE REVIEW

**Comment by entando-service** [comment]
All is Well

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by pietrangelo** [comment]
retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by pietrangelo** [comment]
retest this please

**Comment by entando-service** [comment]
All is Well

**Comment by entando-service** [comment]
All is Well

**Pull request merged**
