### PR TITLE
EN6-210 Test created trying to find the problem. No problem found so …

### PR DESCRIPTION
**Pull request by BrenoQVDS**
…far.

### CODE REVIEW

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by BrenoQVDS** [comment]
Please retest this

**Comment by BrenoQVDS** [comment]
Retest this please

**Comment by entando-service** [comment]
All is Well

**Comment by entando-service** [comment]
All is Well

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by BrenoQVDS** [comment]
This will work only when https://github.com/entando/entando-core/pull/852 is approved

**Comment by ffleandro** [comment]
Retest this please

**Comment by entando-service** [comment]
All is Well

**Pull request merged**
