### PR TITLE
ENG-641: Filter of Contents by Boolean attributes (v5.3.0)

### PR DESCRIPTION
**Pull request by eugeniosant**
This pr needs merge of PR https://github.com/entando/entando-core/pull/907

### CODE REVIEW

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by eugeniosant** [comment]
retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by eugeniosant** [comment]
retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by pietrangelo** [comment]
retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by pietrangelo** [comment]
retest this please

**Comment by entando-service** [comment]
All is Well

**Pull request merged**
