### PR TITLE
ENG-442 Revert "ENG-442 update tests for csrf enable in spring security (#637)"

### PR DESCRIPTION
**Pull request by BrenoQVDS**
This reverts commit 6d70b224ceb7a381b85dd4a540d7d69d346442b8.

### CODE REVIEW

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by BrenoQVDS** [comment]
Retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by BrenoQVDS** [comment]
Retest this please

**Pull request merged**
