### PR TITLE
ENG-731-admin-console-cms- class added on content finding + datatabl…

### PR DESCRIPTION
**Pull request by DMinnai**
added class on content finding + datatables setting updated

### CODE REVIEW

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by eugeniosant** [comment]
retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by eugeniosant** [comment]
@DMinnai Wrong target branch (v5.0.3)

**Pull request closed without merging**
