### PR TITLE
Performance improvements (master)

### PR DESCRIPTION
**Pull request by eugeniosant**
This PR contains several performance improvements especially for page management, category management, i18n label management, content management and CMS resources.
This PR needs merge of PR https://github.com/entando/entando-core/pull/842/files

### CODE REVIEW

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by eugeniosant** [comment]
retest this please

**Comment by entando-service** [comment]
All is Well

**Pull request merged**
