### PR TITLE
EN6-143 Resolving ambiguity for Attributes that implements IndexableA…

### PR DESCRIPTION
**Pull request by BrenoQVDS**
…ttributeInterface and should not support indexable option
This should be reviewed with the other PR: https://github.com/entando/entando-core/pull/832

### CODE REVIEW

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by BrenoQVDS** [comment]
This PR should work only when the PR for entando-core is merged to master

**Comment by BrenoQVDS** [comment]
Retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by ffleandro** [comment]
Retest this please

**Comment by entando-service** [comment]
All is Well

**Pull request merged**
