### PR TITLE
ENG-683 Page Configuration Permissions

### PR DESCRIPTION
**Pull request by ffleandro**
Added test coverage with appropriate permissions to page configuration with cms widgets

### CODE REVIEW

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by BrenoQVDS** [comment]
Retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by BrenoQVDS** [comment]
Retest this please

**Comment by entando-service** [comment]
All is Well

**Pull request merged**
